### ISSUE TITLE
Zig support 

### ISSUE THREAD

**Issue by watzon** [pechorin/any-jump.vim#11]
First of all, this is amazing. Makes navigating code so much easier. I noticed support for [zig](https://ziglang.org) is missing though, which I know is to be expected. It's a lesser known language. Just thought I'd drop an issue here. I'm going to see if I can add it myself right now and get a PR in.

**Comment by pechorin** [comment]
Thanks for response, @watzon :)

Currently i worked on vim support and some minor engine updates and changes, so i'm not in "new language support" phase :) I think new languages support is for next releases (maybe 1+ month from now). So i will add zig to "new languages list" in my next plans, but not for now (too many work should be done).

Adding new unsupported by rg/ag languages is not so hard, but some any-jump updates should be done, because currently any-jump based and ripgrep filetypes, so for new unsupported by ripgrep languages  special mapping (`rg --type-add` or smth ...) should be added. This is not so hard and i think i will add this modification to source code sone. I will notify you in this thread :)

**Comment by watzon** [comment]
Sounds great! I’m going to try and figure out adding a language as things are now and see if I can get zig added so I can use it. A contributing guide would be an awesome addition as well.

**Comment by pechorin** [comment]
@watzon now you can implement you own language support. look at new vars:

- `s:non_standard_ft_extensions_map` inside `autoload/search.vim`
- `s:filetypes_comments_map` inside `autoload/search.vim`
- `s:non_standard_ft_names` inside `autload/lang_map.vim` (additionally)
